# Generated by Django 4.2.19 on 2025-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=20),
        ),
    ]
