# Generated by Django 4.2.19 on 2025-05-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='offer',
        ),
    ]
