# Generated by Django 4.2.19 on 2025-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('served', 'Served'), ('delivered', 'Delivered'), ('take-away', 'Take-away')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('done', 'Done'), ('canceledCanceled', 'Canceled')], max_length=30),
        ),
    ]
