# Generated by Django 4.2.19 on 2025-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_address_alter_delivery_delivery_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
