# Generated by Django 4.2.19 on 2025-05-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_image'),
        ('orders', '0005_delivery_notified_order_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
    ]
