# Generated by Django 5.2.1 on 2025-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delivery_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
