# Generated by Django 4.2.19 on 2025-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_discounted_total_order_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discounted_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
